"""AUTO-GENERATED by calibrate.py — do not edit by hand.

Re-derived 2026-05-31 01:13 from 8 session(s): 185 CONFIRMs,
184 graded / 1 ungraded (insufficient forward window).

core/config.py merges these over the hand-coded fallbacks at import time.
Regenerate with: python calibrate.py
"""
from __future__ import annotations

# (setup_label_exact, regime_substring, action). action in
# {"BLOCK", "REQUIRE_CONV_<n>"}. Trailing comment = uncensored n and hit.
CALIBRATED_REGIME_RULES: list[tuple[str, str, str]] = [
    # (no pair cleared min-sample AND underperformed)
]

# (setup, regime) pairs that cleanly recovered (n >= MIN_SAMPLE_GATE
# AND hit >= 40%). config.py DROPS any hand rule on these — that's how a
# setup whose suppression is no longer justified gets un-gated. A merely
# mediocre setup (WATCH band) is NOT here, so its hand block survives.
CALIBRATED_RELAX: list[tuple[str, str]] = [
    ('EXHAUSTION REV L', 'NORMAL'),
    ('EXHAUSTION REV S', 'NORMAL'),
]

# Conviction factor weights overriding the hand defaults, derived from
# each factor's realised MFE lift (only where present AND absent both
# clear MIN_FACTOR_SAMPLE). config.py merges these — non-circular, so
# auto-applied. Factors not here keep their hand weight.
CALIBRATED_CONVICTION_WEIGHTS: dict[str, int] = {
    'EXH'   : 2,
    'DIV'   : 1,
}

# ADVISORY ONLY — config.py does NOT import these. Re-deriving the
# floor from MFE magnitudes graded against that same floor is mildly
# circular, so floors stay hand-set in config; this is a committed
# reference to eyeball when deciding whether to hand-adjust them.
# pctile of realised MFE, clamped to [0.5x, 2x] of the current floor.
CALIBRATED_MFE_FLOORS: dict[str, float] = {
    'BANKNIFTY'   : 22.0    ,  # n=35, raw_p33=21.6
    'BN_FUT'      : 30.0    ,  # n=45, raw_p33=29.8
    'HDFCBANK'    : 2.0     ,  # n=13, raw_p33=0.6
    'NIFTY'       : 8.0     ,  # n=25, raw_p33=8.4
    'NIFTY_FUT'   : 13.0    ,  # n=37, raw_p33=12.5
}

